### PR TITLE
Fix #373 by avoiding duplicating static C++ code

### LINKED ISSUE #373: Duplicate definitions of OptimResultNimbleList functions
@perrydv found that test-optim.R is failing on OS X due to dupliciated definitions of `new_OptimResultNimbleList`, `OptimResultNimbleList_castPtrPtrToNamedObjectsPtrSEXP`, and `OptimResultNimbleList_castDerivedPtrPtrToPairOfPtrsSEXP`: there are versions in both generated code and static code. Note that gcc on linux appears to allow the duplicated definitions.

This is probably an issue with the `predefined` flag not being respected during search for needed methods.

### PR DESCRIPTION
**Pull request by fritzo**
This fixes #373 by avoiding duplicate generation of C++ code for predefined `nimbleList` types.

### CODE REVIEW

File: packages/nimble/R/cppDefs_nimbleList.R [hunk 1]
```diff
@@ -12,14 +12,8 @@ cppNimbleListClass <- setRefClass('cppNimbleListClass',
...
                                       getDefs = function() {
-                                        ans <- if(predefined){ ## prevents redefinition of EIGEN_EIGENCLASS or EIGEN_SVDCLASS
-                                          if(inherits(SEXPfinalizerFun, 'uninitializedField'))
-                                            list(SEXPgeneratorFun)
-                                          else
-                                            list(SEXPgeneratorFun, SEXPfinalizerFun)
-                                        }
-                                               else callSuper()
-                                        c(ans, ptrCastFun, ptrCastToPtrPairFun)
+                                        if(predefined) return(NULL)  ## Prevents redefinition of nimbleList classes that are predefined in inst/.
```
Comment (NLMichaud) [inline packages/nimble/R/cppDefs_nimbleList.R]: can return(list()) here

**Comment by fritzo** [comment]
@perrydv This should be working now :smile: Can you please verify on your machine?

The solution Nick and I found was to:
- Generate as much as possible of `optimResultNimbleList`, `optimControlNimbleList`, `svdNimbleList`, and `eigenNimbleList`
- Avoid generating the class definitions for `svdNimbleList`, and `eigenNimbleList`, since they have a custom class hierarchy to support R and C calling.
