### PR TITLE
Fixes #460 remove default logical arguments from templated calculate etc.

### LINKED ISSUE #460: `model$calculate(nodes[i])` does not compile.
On devel and in 0.6-5, it seems like `model$calculate(nodes[i])` will not compile inside of a `nimbleFunction`.  However, `model$calculate(nodes[c(i)])` will.  An example on a very simple model is included below:
```
testCode1 <- nimbleCode({
  x ~ dnorm(0, 1)
  y ~ dnorm(x, 1)
})
testMod1 <- nimbleModel(code = testCode1, data = list(y = 0),
                      inits = list(x = 1))
compileNimble(testMod1)

testFxn <- nimbleFunction(
  setup = function(model, calcNodes){
    n <- length(calcNodes)
  },
  run = function(){
    for(i in 1:n){
      model$calculate(calcNodes[i])
    }
  }
)
testFxnInstance <- testFxn(testMod1, c('x', 'y'))
### This function fails to compile due to the call to model$calculate(calcNodes[i])
ctestFxnInstance <- compileNimble(testFxnInstance, project = testMod1, showCompilerOutput = TRUE)

testFxn2 <- nimbleFunction(
  setup = function(model, calcNodes){
    n <- length(calcNodes)
  },
  run = function(){
    for(i in 1:n){
      model$calculate(calcNodes[c(i)])
    }
  }
)
testFxnInstance2 <- testFxn2(testMod1, c('x', 'y'))
### This function compiles, since call has been changed to model$calculate(calcNodes[c(i)])
ctestFxnInstance2 <- compileNimble(testFxnInstance2, project = testMod1, showCompilerOutput = TRUE, resetFunctions = TRUE)
```

### PR DESCRIPTION
**Pull request by perrydv**
Fixes #460. 

This PR is to run tests.  Prior to merging, a regression test of the fixed issue should be added.

Failure of `model$calculate(nodes[i])` occurred because of unintended disambiguation of overloaded (including templated) C++ versions of `calculate`.  Removing an unnecessary default argument fixes the problem.

### CODE REVIEW

File: packages/nimble/inst/include/nimble/nimbleEigenNimArr.h [hunk 1]
```diff
@@ -86,7 +86,7 @@ void setValuesIndexRange(NimArrBase<T> &nimArr, ManyVariablesMapAccessor &MVA, c
 
 
 template<typename Derived>
-double calculate(NodeVectorClassNew &nodes, const Derived &indices, bool logical=false) {
+double calculate(NodeVectorClassNew &nodes, const Derived &indices, bool logical) { // remove default value of logical to fix function overloading issues
```
Comment (fritzo) [inline packages/nimble/inst/include/nimble/nimbleEigenNimArr.h]: Remove comment. It belongs as a comment on the PR, not a permanent comment in the code.

Comment (fritzo) [inline packages/nimble/inst/include/nimble/nimbleEigenNimArr.h]: Specifically, the function does not "remove anything", it is your PR that "removes" something.
